### ISSUE TITLE
Permanent loading icon for module

### ISSUE THREAD

**Issue by iamkroot** [crux-bphc/CMS-Android#127]
App permanently shows the loading animation for the module (Quiz-1 Date module in screenshot).
Course: BITS F314
<img src="https://user-images.githubusercontent.com/29517049/65828401-30143000-e2b8-11e9-8106-dbf81c52d00b.png" alt="Loading animation" width=300px>

**Comment by abhijeetviswa** [comment]
By default, the App ships with a bunch of svg+xml images to be used for the icons. However, if, for a given module, an icon is not included, then the default one used by Moodle is used instead. Moodle servers svg+xml images as well. However, Picasso, the libray we use for Image loading, doesn't support SVGs. I've only done limited research, but it seems no library supports it on its own (including Glide). They all require SVG-Android to be used as well. 

We'll need to either use SVG-Android with Picasso (resources for which I have no found) or migrate to Glide (implementation seems to be easier). 

An easier work around for this specific bug would be to just include the missing icon resource. However, we still need to fix the root cause behind this bug.

**Comment by SKrPl** [comment]
@abhijeetviswa go through [fresco](https://github.com/facebook/fresco).

**Comment by abhijeetviswa** [comment]
Neither Fresco nor Glide supports SVGs natively. I decided to go with Glide in #253 for no particular reason.
