### ISSUE TITLE
JsonsSyntaxException in Courserequesthandler.getcourselist

### ISSUE THREAD

**Issue by harsu-ag** [crux-bphc/CMS-Android#37]
The exception is mostly raised when it tries to cast a jsonObject returned as response into a list of Courses where it expects a JSONarray. 

Why it happens. When it happens. 
![screenshot_20171207-194302](https://user-images.githubusercontent.com/12862633/33719830-0bde00f0-db88-11e7-97b8-a15375885c9c.png)

**Comment by TheGamer007** [comment]
This issue was faced by a user not registered in any courses. He circumvented the issue by enrolling via the website, after which the app functioned normally. The attached logs were provided by him.

As per the relevant code in `CourseRequestHandler`, in the case of no courses being registered, the `responseString` should be `[]` (an empty JSON Array) and is parsed correctly.  Bug could not be replicated with another account, which was not registered in any courses. Unclear why it might have happened to him. 

A relevant ongoing PR is #50, but unclear if it has covered all possible error cases.

![cms logs](https://user-images.githubusercontent.com/22165670/44626366-84701200-a938-11e8-91b0-580dd9e8d9c6.jpg)
