### ISSUE TITLE
Unusual Forum Ordering

### ISSUE THREAD

**Issue by TheGamer007** [crux-bphc/CMS-Android#83]
The standard `Discussion`s in a `Forum` are in descending order of time i.e. latest on top. Opening the `ForumFragment` and fetching the discussions uses a paginated call that returns them in this sorted order.

On the other hand, the "refresh" options in both the `CourseSectionFragment` and `MyCoursesFragment` use a call that retrieves all discussions at once. Examining the response on Postman shows that these are also sorted.

However, in the app, refreshing on the `CourseSectionFragment` and then loading cached data of a Forum (by disconnecting from the internet before navigating there) shows that they are not in proper order. This is not seen when reloading from `MyCoursesFragment` for some reason, even though the code is exactly the same. 

This is not a major bug yet, but it is better to look into the network calls and Realm calls so that any future bugs can be prevented.

**Comment by abhijeetviswa** [comment]
Another bug was caused due to the difference in pagination on the `DiscussionFragment` and in `NotificationService`. Pagination in `DiscussionFragment` meant that Realm would keep getting cleared. This resulted in the  `NotificationService` creating notifications for discussions that weren't in the paginated response. This was fixed in `489559995ee657505edf1d14a1356346238380b0` by simply not using pagination. Probably not the best solution, but it works for now. 

Closing this issue for now.
