### ISSUE TITLE
Change notification method to 'push' based model

### ISSUE THREAD

**Issue by TheGamer007** [crux-bphc/CMS-Android#89]
Currently, the app [polls](https://zapier.com/developer/documentation/v2/polling/) `GET` endpoints and compares the latest data with the offline, cached data and generates notifications accordingly. This happens at a fixed hourly interval. 

It is desirable to migrate to a push based notification model due to its benefits. As the above link mentions, REST Hooks are one way to go about it. While it seems like Moodle has [abandoned this](https://docs.moodle.org/dev/Hooks_spec), there seem to be [plugins](https://moodle.org/plugins/local_webhooks) that can provide the required functionality.

The [Moodle app notifications](https://docs.moodle.org/35/en/Moodle_app_notifications) page provides information on how it is handled in the official app, and even has an "Installing your own notifications infrastructure" section that may be useful. It relies on [AirNotifier](http://airnotifier.github.io/), and seems like a straightforward and promising solution.

**Comment by abhijeetviswa** [comment]
Will the administration be ready to add plugins for this?

**Comment by SKrPl** [comment]
@abhijeetviswa They won't mind if it's better, and push model >> pull model for notifications.

**Comment by harsu-ag** [comment]
Do apply push based service if possible. As we implemented pull based
service just because of time crunch of 1 month.

Give them numbers like - 2k devices polling every hour vs push to only
subscribers.

On another note, push service might cost us a little based on the
notification traffic especially during exam times.

**Comment by abhijeetviswa** [comment]
Update on this: I've been in touch with the TD nucleus. They've given me access and free reign to setup push notifications for Moodle. However, the issue is the lack of documentation to set this up.

Moodle uses Airnotifier as an intermediary to handle push notifications. [This branch](https://github.com/moodlehq/airnotifier/tree/moodle2) of their Airnotifier fork is what they've asked to install in their documentation. However, the branch itself is old, and so is the documentation. I went ahead and [started a discussion](https://moodle.org/mod/forum/discuss.php?d=404014) on their community forum asking for help. However, there have been no responses so far.

I plan to try doing this locally now. Trying to figure this out on my own might be easier than waiting for a reply on their forum. Maybe we can get a tutorial out of it.

**Comment by abhijeetviswa** [comment]
WIP for the plugin has begun: [abhijeetviswa/moodle-local_extendednotifs](https://github.com/abhijeetviswa/moodle-local_extendednotifs)
